spring:
  application:
    name: product-manager
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

jwt:
  access-token-expiration: 900
  refresh-token-expiration: 604800

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
